Repository CaptainFact/captain-fact-frontend, pull requests merged in 2018-08, with the labels that each got.

#164 Allow null comment user (anonymous)
  app/components/Comments/CommentDisplay.jsx
  app/components/Users/DeleteUserModal.jsx
  app/i18n/en/main.js
  app/i18n/fr/main.js
  app/state/video_debate/comments/record.js
  app/state/video_debate/comments/selectors.js
  app/styles/_components/VideoDebate/comments/comment.sass
Labels: UI / UX, feature

#169 Clarify documentation
  app/assets/assets/help/en/contributionGuidelines.md
  app/assets/assets/help/fr/contributionGuidelines.md
Labels: content, good first issue

#178 Add discord bot to OpenGraph user agents
  config/nginx.conf
Labels: enhancement

#177 Bold text + colorful icon on partner's video cards
  app/components/Videos/VideoCard.jsx
  app/i18n/en/videoDebate.js
  app/i18n/fr/videoDebate.js
  app/styles/_components/Videos/card.sass
Labels: UI / UX

#182 Use external link icon on speaker's page wiki links
  app/components/Speakers/SpeakerPage.jsx
Labels: UI / UX, enhancement

#184 Af type="email" on email fields
  app/components/Users/UserFormFields.jsx
Labels: UI / UX, enhancement

#186 Reduce username margin-bottom and fix icon width when collapsed
  app/styles/_components/App/sidebar.sass
Labels: UI / UX, enhancement

#188 Fix display bug with self-sourcing on small devices
  app/styles/_components/statements.sass
Labels: UI / UX, bug

#189 Improvement/update dependencies
  package-lock.json
  package.json
Labels: enhancement

#185 Fix help page colors and add missing translation
  app/components/Help/Help.jsx
  app/i18n/en/help.js
  app/i18n/fr/help.js
Labels: UI / UX, enhancement

#183 Refactor CommentDisplay and CommentsContainer (now CommentsList)
  app/components/Comments/CommentAction.jsx
  app/components/Comments/CommentActions.jsx
  app/components/Comments/CommentContent.jsx
  app/components/Comments/CommentDisplay.jsx
  app/components/Comments/CommentHeader.jsx
  app/components/Comments/CommentsContainer.jsx
  app/components/Comments/CommentsList.jsx
  app/components/Comments/CommentsListExpender.jsx
  app/components/Comments/CommentsListHeader.jsx
  app/components/Comments/IconModerationPending.jsx
  app/components/Comments/OtherCommentActions.jsx
  app/components/Comments/OwnCommentActions.jsx
  app/components/Comments/Vote.jsx
  app/components/Comments/index.js
  app/components/Statements/Statement.jsx
  app/constants.js
  app/state/video_debate/comments/selectors.js
Labels: refactor

#187 Move LanguageSelector up in sidebar and add it to settings page
  app/components/App/LanguageSelector.jsx
  app/components/App/Sidebar.jsx
  app/components/Users/ThirdPartyAccountLinker.jsx
  app/components/Users/UserSettings.jsx
  app/i18n/en/user.js
  app/i18n/fr/user.js
Labels: UI / UX, enhancement

#179 Feature/activity log
  app/API/graphql_api.js
  app/components/App/Sidebar.jsx
  app/components/Users/ActivityLog.jsx
  app/components/Users/User.jsx
  app/components/UsersActions/ActionDiff.jsx
  app/components/UsersActions/ActionIcon.jsx
  app/components/UsersActions/ActionsTable.jsx
  app/components/UsersActions/EntityLink.jsx
  app/components/UsersActions/EntityTitle.jsx
  app/components/UsersActions/UserAction.jsx
  app/components/Utils/Button.jsx
  app/components/Utils/MessageView.jsx
  app/components/Utils/PaginationMenu.jsx
  app/config.js
  app/i18n/en/history.js
  app/i18n/en/main.js
  app/i18n/en/user.js
  app/i18n/fr/history.js
  app/i18n/fr/main.js
  app/i18n/fr/user.js
  app/index.jsx
  app/lib/actions_context.js
  app/lib/cf_routes.js
  app/router.jsx
  app/styles/_components/User/activity_log.sass
  app/styles/_components/UsersActions/user_action.sass
  app/styles/_global/spinner.sass
  app/styles/application.sass
  config/env/dev.env
  config/env/prod.env
  config/env/staging.env
  package-lock.json
  package.json
  webpack.config.js
  webpack.production.config.js
Labels: feature

#193 Make homepage statistics dynamic
  app/components/Home/AllContributors.jsx
  app/components/Home/Home.jsx
  app/components/Home/Statistics.jsx
  app/components/Pages/index.js
  app/router.jsx
Labels: enhancement

#194 Add `Artist` and `GoodVibes` achievements
  app/assets/assets/achievements/artist.jpg
  app/assets/assets/achievements/default.png
  app/assets/assets/achievements/goodVibes.jpg
  app/assets/assets/help/en/achievements.md
  app/assets/assets/help/fr/achievements.md
  app/components/Users/Achievement.jsx
  app/i18n/en/achievements.js
  app/i18n/fr/achievements.js
  app/styles/_components/User/achievements.sass
  webpack.loaders.js
Labels: feature, graphic design

#199 More reputation tooltips
  .travis.yml
  app/components/Speakers/AddSpeakerForm.jsx
  app/components/Speakers/EditSpeakerForm.jsx
  app/components/Speakers/SpeakerForm.jsx
  app/components/Speakers/SpeakerPreview.jsx
  app/components/Speakers/index.js
  app/components/Statements/SpeakerComments.jsx
  app/components/Statements/Statement.jsx
  app/components/Statements/StatementComments.jsx
  app/components/Statements/StatementContainer.jsx
  app/components/Statements/StatementHeader.jsx
  app/components/Statements/StatementsList.jsx
  app/components/Statements/VerificationsOriginHeader.jsx
  app/components/Utils/ReputationGuardTooltip.jsx
  app/components/Utils/__tests__/__snapshots__/ReputationGuardTooltip.spec.jsx.snap
  app/components/VideoDebate/ColumnVideo.jsx
  app/lib/name_formatter.js
  app/styles/_components/Utils/reputation_guard_tooltip.sass
  app/styles/_components/VideoDebate/video_debate.sass
  app/styles/_global/icons.sass
  app/styles/_libraries_overrides/react-select.sass
  app/styles/application.sass
Labels: UI / UX, enhancement

#192 Store Q letter in wikidata_item_id + Disable speakers validation feature
  app/components/Speakers/SpeakerPreview.jsx
  app/components/Videos/VideoCard.jsx
  app/state/speakers/effects.js
  app/state/speakers/record.js
  app/state/videos/__tests__/__fixtures__/videos.json
  app/state/videos/__tests__/__snapshots__/reducer.spec.js.snap
Labels: enhancement
